### ISSUE TITLE
fix the game tests

### ISSUE THREAD

**Issue by DGDegrassi** [Checkmates-Chess/Checkmateschess#3]
The game tests in the test branch still fail.  I'd like to merge the tests in to the master but don't want everything to fail whenever something is pushed because the games tests don't work.   I guess either we comment them out for now or fix them.

**Comment by DGDegrassi** [comment]
I've gone and commented it out and will merge it.  They still need to be fixed however, possibly in a new branch

**Comment by evan10003** [comment]
I have functioning games tests in the joining_game branch. they can be fleshed out for cases like user is not logged in, etc., but it's a start.

**Comment by WildoBro** [comment]
I had to comment out the games#update test, as it was not supporting a feature I added on the chessboard branch (randomly assigning player color).

I will take a crack at correcting the games#update test in the morning.
